dataset:
  root: '/root/storage/dataset/kspon'
  train: 'data/Ksponspeech/train_0112.trn'
  valid: 'data/Ksponspeech/test_0110.trn'
  test: 'data/Ksponspeech/val_1125_.trn'

setting:
  model_type: 'transducer'
  opt_type: 'noam'
  loss_type: 'rnnt_loss'
  device: 'cuda'

model:
  out_dim: ???
  feat_extractor: 'vgg'
  enc_n_layers: 14
  dec_n_layers: 6
  hidden_dim: 512 
  filter_dim: 2048
  n_head: 1
  dropout_rate: 0.1
  max_len: 150
  pad_id: 0
  sos_id: 1 
  eos_id: 2

optimizer:
  d_model: 512
  warmup: 25000
  factor: 1

train:
  device: 'cuda'
  batch_size: 10
  epochs: 600
  save_epoch: 2
  
feature:
  spec: 
    sample_rate: 16000
    n_mels: 80
    n_fft: 512
    hop_length: 256
    win_length: 512
    normalized: False
  augment:
    spec_augment: 0.5
    time_shifting: 0
    noise_injecting: 0
  